compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "element-plus@*":
    dependencies:
      "@vue/shared": "*"
  eslint-plugin-import-x@*:
    dependencies:
      '@typescript-eslint/parser': '*'
      eslint-import-resolver-typescript: '*'
